// Generated by build.py. Do not edit.
var agents = [
  {
    id: "opencode",
    name: "OpenCode",
    status: "Active",
    organization: "Anomaly",
    versionReviewed: "0.5.0",
    lastUpdated: "2026-07",
    addedDate: "2025-12",
    path: "/agents/opencode/",
    order: 1
  },
  {
    id: "antigravity",
    name: "Antigravity",
    status: "Active",
    organization: "Google",
    versionReviewed: "0.4.0",
    lastUpdated: "2026-07",
    addedDate: "2026-01",
    path: "/agents/antigravity/",
    order: 2
  },
  {
    id: "codex",
    name: "Codex",
    status: "Active",
    organization: "OpenAI",
    versionReviewed: "0.10.0",
    lastUpdated: "2026-07",
    addedDate: "2024-10",
    path: "/agents/codex/",
    order: 3
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI",
    status: "Occasional",
    organization: "Google",
    versionReviewed: "1.2.0",
    lastUpdated: "2026-07",
    addedDate: "2025-04",
    path: "/agents/gemini-cli/",
    order: 1
  },
  {
    id: "claude-code",
    name: "Claude Code",
    status: "Occasional",
    organization: "Anthropic",
    versionReviewed: "0.12.0",
    lastUpdated: "2026-07",
    addedDate: "2025-03",
    path: "/agents/claude-code/",
    order: 2
  },
  {
    id: "aider",
    name: "Aider",
    status: "Occasional",
    organization: "Paul Gauthier",
    versionReviewed: "0.72.0",
    lastUpdated: "2026-07",
    addedDate: "2024-06",
    path: "/agents/aider/",
    order: 3
  },
  {
    id: "warp",
    name: "Warp",
    status: "Archived",
    organization: "Warp Inc.",
    versionReviewed: "2026.06",
    lastUpdated: "2026-06",
    addedDate: "2024-09",
    path: "/agents/warp/",
    order: 1
  },
  {
    id: "cursor",
    name: "Cursor",
    status: "Archived",
    organization: "Cursor Inc.",
    versionReviewed: "0.46.x",
    lastUpdated: "2026-06",
    addedDate: "2024-08",
    path: "/agents/cursor/",
    order: 2
  },
  {
    id: "continue",
    name: "Continue",
    status: "Archived",
    organization: "Continue",
    versionReviewed: "1.2.0",
    lastUpdated: "2026-06",
    addedDate: "2024-07",
    path: "/agents/continue/",
    order: 3
  },
  {
    id: "goose",
    name: "Goose",
    status: "Archived",
    organization: "Block",
    versionReviewed: "1.5.0",
    lastUpdated: "2026-06",
    addedDate: "2025-02",
    path: "/agents/goose/",
    order: 4
  },
  {
    id: "openhands",
    name: "OpenHands",
    status: "Archived",
    organization: "OpenHands",
    versionReviewed: "0.9.0",
    lastUpdated: "2026-06",
    addedDate: "2025-01",
    path: "/agents/openhands/",
    order: 5
  },
  {
    id: "cline",
    name: "Cline",
    status: "Archived",
    organization: "Cline",
    versionReviewed: "3.4.0",
    lastUpdated: "2026-06",
    addedDate: "2025-01",
    path: "/agents/cline/",
    order: 6
  },
  {
    id: "roo-code",
    name: "Roo Code",
    status: "Archived",
    organization: "Roo Code",
    versionReviewed: "2.0.0",
    lastUpdated: "2026-06",
    addedDate: "2025-03",
    path: "/agents/roo-code/",
    order: 7
  },
  {
    id: "amp",
    name: "Amp",
    status: "Archived",
    organization: "Sourcegraph",
    versionReviewed: "0.3.0",
    lastUpdated: "2026-06",
    addedDate: "2026-02",
    path: "/agents/amp/",
    order: 8
  },
  {
    id: "crush",
    name: "Crush",
    status: "Archived",
    organization: "Charm",
    versionReviewed: "0.2.0",
    lastUpdated: "2026-06",
    addedDate: "2026-03",
    path: "/agents/crush/",
    order: 9
  },
  {
    id: "qwen-code",
    name: "Qwen Code",
    status: "Archived",
    organization: "Alibaba Cloud",
    versionReviewed: "2.5.0",
    lastUpdated: "2026-06",
    addedDate: "2025-05",
    path: "/agents/qwen-code/",
    order: 10
  }
];
